services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: nutricoreiq
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1596387413
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3

  test_db:
    image: postgres
    environment:
      POSTGRES_DB: test_nutricoreiq
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5435:5432"

  redis:
    image: redis:alpine
    ports:
      - "6378:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    command: redis-server --save 60 1 --loglevel warning

volumes:
  pgdata:
  redisdata:
