pg_stat_user_tables:
  query: |
    SELECT
      schemaname,
      relname,
      seq_scan,
      seq_tup_read,
      idx_scan,
      idx_tup_fetch,
      n_tup_ins,
      n_tup_upd,
      n_tup_del,
      n_tup_hot_upd,
      n_live_tup,
      n_dead_tup,
      vacuum_count,
      autovacuum_count,
      analyze_count,
      autoanalyze_count
    FROM pg_stat_user_tables;
  metrics:
    - relname:
        usage: "LABEL"
        description: "Table name"
    - schemaname:
        usage: "LABEL"
        description: "Schema name"
    - seq_scan:
        usage: "COUNTER"
        description: "Sequential scans"
    - idx_scan:
        usage: "COUNTER"
        description: "Index scans"
    - n_tup_ins:
        usage: "COUNTER"
        description: "Inserted tuples"
    - n_tup_upd:
        usage: "COUNTER"
        description: "Updated tuples"
    - n_tup_del:
        usage: "COUNTER"
        description: "Deleted tuples"
    - n_live_tup:
        usage: "GAUGE"
        description: "Estimated live tuples"

pg_stat_database:
  query: |
    SELECT
      datname,
      numbackends,
      xact_commit,
      xact_rollback,
      blks_read,
      blks_hit,
      tup_returned,
      tup_fetched,
      tup_inserted,
      tup_updated,
      tup_deleted,
      conflicts,
      temp_files,
      temp_bytes,
      deadlocks,
      blk_read_time,
      blk_write_time
    FROM pg_stat_database;
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - numbackends:
        usage: "GAUGE"
        description: "Number of backends currently connected"
    - xact_commit:
        usage: "COUNTER"
        description: "Transactions committed"
    - xact_rollback:
        usage: "COUNTER"
        description: "Transactions rolled back"
    - blks_read:
        usage: "COUNTER"
        description: "Disk blocks read"
    - blks_hit:
        usage: "COUNTER"
        description: "Buffer hits"
    - tup_returned:
        usage: "COUNTER"
        description: "Tuples returned"
    - tup_fetched:
        usage: "COUNTER"
        description: "Tuples fetched"
    - tup_inserted:
        usage: "COUNTER"
        description: "Tuples inserted"
    - tup_updated:
        usage: "COUNTER"
        description: "Tuples updated"
    - tup_deleted:
        usage: "COUNTER"
        description: "Tuples deleted"
    - conflicts:
        usage: "COUNTER"
        description: "Conflicts"
    - deadlocks:
        usage: "COUNTER"
        description: "Deadlocks"
    - blk_read_time:
        usage: "GAUGE"
        description: "Time spent reading blocks"
    - blk_write_time:
        usage: "GAUGE"
        description: "Time spent writing blocks"

pg_stat_bgwriter:
  query: |
    SELECT
      checkpoints_timed,
      checkpoints_req,
      checkpoint_write_time,
      checkpoint_sync_time,
      buffers_checkpoint,
      buffers_clean,
      maxwritten_clean,
      buffers_backend,
      buffers_backend_fsync,
      buffers_alloc
    FROM pg_stat_bgwriter;
  metrics:
    - checkpoints_timed:
        usage: "COUNTER"
        description: "Timed checkpoints"
    - checkpoints_req:
        usage: "COUNTER"
        description: "Requested checkpoints"
    - checkpoint_write_time:
        usage: "COUNTER"
        description: "Checkpoint write time"
    - checkpoint_sync_time:
        usage: "COUNTER"
        description: "Checkpoint sync time"
    - buffers_checkpoint:
        usage: "COUNTER"
        description: "Buffers written during checkpoints"
    - buffers_clean:
        usage: "COUNTER"
        description: "Buffers written by bgwriter"
    - buffers_backend:
        usage: "COUNTER"
        description: "Buffers written by backend"

pg_stat_statements:
  query: |
    SELECT
      queryid,
      query,
      calls,
      total_time,
      rows,
      shared_blks_hit,
      shared_blks_read,
      shared_blks_dirtied,
      shared_blks_written
    FROM pg_stat_statements;
  metrics:
    - queryid:
        usage: "LABEL"
        description: "Query ID"
    - calls:
        usage: "COUNTER"
        description: "Number of times executed"
    - total_time:
        usage: "COUNTER"
        description: "Total execution time"
    - rows:
        usage: "COUNTER"
        description: "Rows returned"
    - shared_blks_hit:
        usage: "COUNTER"
        description: "Shared blocks hit"
    - shared_blks_read:
        usage: "COUNTER"
        description: "Shared blocks read"

pg_locks:
  query: |
    SELECT mode, COUNT(*) AS count FROM pg_locks GROUP BY mode;
  metrics:
    - mode:
        usage: "LABEL"
        description: "Lock mode"
    - count:
        usage: "GAUGE"
        description: "Number of locks held per mode"

pg_replication:
  query: |
    SELECT application_name, state, sync_state, write_lag, flush_lag, replay_lag
    FROM pg_stat_replication;
  metrics:
    - application_name:
        usage: "LABEL"
        description: "Standby name"
    - state:
        usage: "LABEL"
        description: "Replication state"
    - sync_state:
        usage: "LABEL"
        description: "Sync state"
    - write_lag:
        usage: "GAUGE"
        description: "Write lag"
    - flush_lag:
        usage: "GAUGE"
        description: "Flush lag"
    - replay_lag:
        usage: "GAUGE"
        description: "Replay lag"
